[package]
name = "suilend"
version = "0.0.1"
published-at = "0x157dbf1830dab58ec67e025c1200a32a22a31150beba4d3de8e39571547f8cc2"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true
 
[dependencies.Pyth]
git = "https://github.com/solendprotocol/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "98e218c64bb75cf1350eb7b021e1ffcc3aedfd62"

[addresses]
sui = "0x2"
# suilend = "0x0"
suilend = "0xf95b06141ed4a174f239417323bde3f209b972f5930d8521ea38a52aff3a6ddf"
